### ISSUE TITLE
Confusing timer display

### ISSUE THREAD

**Issue by alanz** [zond/diplicity#106]
The "My started games" screen presents a confusing countdown time.

![screenshot_20180415-201627](https://user-images.githubusercontent.com/409607/38781765-a91230ae-40ea-11e8-82af-13385b86b57e.jpg)

The game is of type "classical 1d", but the way the remaining time is appended, it looks like there is a day and 8 hrs remaining.

Diplicity version: 292

(I accidentally created issue 404 on the wrong repo too, https://github.com/stom79/mastalab/issues/404. Lucky number)

**Comment by zond** [comment]
Thanks for the report!

It seems my latest work on adding more icons to the game list broke the layout.

Working on fixing it ...

**Comment by zond** [comment]
Should be fixed in https://github.com/zond/android-diplicity/commit/dbf0f1284c66cf6146b2bd7d70dfea29bd90b5a5.

If you can't wait for the rollout to finish, you can download the newest version at https://github.com/zond/android-diplicity/releases.

**Comment by alanz** [comment]
Looks much better, thanks.
