### ISSUE TITLE
Requesting a draw is counted in stats for losing player

### ISSUE THREAD

**Issue by tttppp** [zond/diplicity#111]
See https://groups.google.com/forum/#!topic/diplicity-talk/6B2Sn8bCsSk

A user who has marked that they would accept a draw gets listed in the game result as having drawn the game.  This is also included in the per-player stats.

Here's an extract from the game result JSON for one of my games - note that there shouldn't be a solo winner and a DIAS member:
```
    "SoloWinnerMember": "France",
    "SoloWinnerUser": "112159747476089937351",
    "DIASMembers": [
      "Austria"
    ],
    "DIASUsers": [
      "104020570100623707683"
    ],
```

**Comment by zond** [comment]
So, the pull request is merged and deployed, but the list of users to update stats for was too big (1318 games, evidently): Call error 5: API request too large: 8746185. Limit for datastore_v3 is: 1572864

We are just going to have to start a job that updates every user :/ Not rocket science, but not exactly the best solution.

**Comment by zond** [comment]
Should be solved once and for all by https://github.com/zond/diplicity/commit/9ca1e65d01224cd7056c26da98447082531ed126
