### ISSUE TITLE
Push notifications are broken by installing on a second device

### ISSUE THREAD

**Issue by tttppp** [zond/diplicity#113]
Interesting bug raised here:
https://groups.google.com/forum/#!topic/diplicity-talk/rLNpv_XNw-U

"Try to switch the push notifications flag off and back on. It helped me when I installed Diplicity on a second device. Looks like only last registered device is receiving them."

I haven't tried reproducing this issue.

**Comment by zond** [comment]
IIRC the server supports multiple devices to send notifications to, but the client overwrites a single destination every time your turn them on.

I.e. it's probably not that hard to fix, and only a client issue.

**Comment by zond** [comment]
Yeah - the server supports multiple devices, but it requires that the client respects that and don't overwrite the tokens of the other devices.

I don't remember what the android client does in this regard.

**Comment by zond** [comment]
This should no longer be the case, anyway.
