### ISSUE TITLE
Reject conflicting moves when clicking RDY

### ISSUE THREAD

**Issue by tttppp** [zond/diplicity#116]
We had a suggestion on Discord to help avoid players giving support/convoy orders that don't match their own move orders.  When a player clicks RDY then the following check is run:
```
For each support or convoy order:
    If the supported or convoyed unit is owned by the current player:
        Check that the order for that unit is consistent with the support/convoy order
```

This would require an extra "consistency validation" method to be added to each order, which could be a no-op for move and hold orders.

It often makes sense to allow conflicting move orders (self-bouncing), but it never really makes sense to allow e.g. convoying your own unit if it is holding.

This validation could be turned off by a "no validation" setting in the future. We already discussed that when talking about better gunboat support.

**Comment by zond** [comment]
This sounds great. Why not make it like a warning, and let the client decide whether to ignore warning, notify user, or reject order?

**Comment by tttppp** [comment]
So the communication would be:
```
RDY -->
    <-- Warning
        (Not RDY)
OK  -->
        (RDY)
```

i.e. If the client ignores the warning then the player is not ready. Otherwise the player may have no chance to respond to the warning if all other players are already ready to resolve.

**Comment by zond** [comment]
Or

RDY(force=no)
WARNING
RDY(force=yes)
OK

Simpler protocol, I suspect

**Comment by tttppp** [comment]
Yes - this sounds like a nicer way to do it. :+1:

**Comment by zond** [comment]
Deprecated by #152
