### ISSUE TITLE
Tribute is only working for Classical variants

### ISSUE THREAD

**Issue by tttppp** [zond/diplicity#140]
For example the graph for a Western World 901 game looks like:
![image](https://user-images.githubusercontent.com/7073263/79835167-282bf280-83a6-11ea-9961-dd3bec741ac2.png)
The Western Frankish Kingdom would have "won" if a draw was accepted earlier in the game.

**Comment by zond** [comment]
Yeah, that's true - what's wrong with that?

**Comment by tttppp** [comment]
The same game now has a graph like:
![image](https://user-images.githubusercontent.com/7073263/80299273-23db4d00-878b-11ea-8da7-4b2ced861319.png)
Fixed :+1:
