### ISSUE TITLE
Validate build orders

### ISSUE THREAD

**Issue by zond** [zond/diplicity#143]
To not allow more than what you may actually build.

**Comment by zond** [comment]
This doesn't make sense with the adjudicator principle of validating orders only on their own merits (would we otherwise validate support orders or convoy orders with their paired orders).

I realize that build/disband orders can only depend on other orders from the SAME player, so it's slightly different, but it goes against the relatively stateless order validation (stateless in so far as it doesn't have a state of other simultaneous orders to care about), which makes it change a bit too much in other ways.

**Comment by tttppp** [comment]
This sounds good for players who want it. Arguably this should happen alongside https://github.com/zond/diplicity/issues/116
