### ISSUE TITLE
Remove metadata from JSON

### ISSUE THREAD

**Issue by spamguy** [zond/diplicity#41]
The average JSON response from an endpoint looks like this right now:

```
{"Name":"started-games","Properties":[],"Desc":[["Started games","Started games, sorted with oldest first."],["Cursor and limit","The list contains at most 64 games.","If there are additional matching games, a 'next' link will be available with a 'cursor' query parameter.","Use the 'next' link to list the next batch of matching games.","To list fewer than 64 games, add an explicit 'limit' query parameter."],["Filters","To show only games with a given variant, add a `variant` query parameter."]],"Type":"List","Links":[{"Rel":"self","URL":"https://diplicity-engine.appspot.com/Games/Started?token=3oufbd5ZxcVX9uGGg162rTHpcc6mS-yC7fgqqgqX6Pa9PmVKRO2FODGGxRvYi3apj2OTvR_TKqS_TMPh1OSxtmkFHAy4CoCjdq0eIZhf1fSdq-JL8aCWipXU8CulgXuVPvbTLh7Z-PenBAWmq5vees63jo8b88euOY3HW8UivGylxUCAggBAbLQX6f33v2rbFcPVC83W4f9p81RWK3qsmwLHh_HTM4XRSVMxu1xKBCK2IfXKxbLDAh5w5d6YkFZjeQGwhsC-tqHw-80L4f3xzK9tSWXpK63ydcU7PpqEkiy2W6Vuhd56A5LnDuEMrg2XFLXLjy3BRzN7lrLFWa5xlRye1Z5rF6UyQY0pTCl-UzDxJsEMLbjd1o0j5e1CDs_7YOCrAnjs5ggaICqnWv3HgXxgCnQuUJfeKF4kf_nhmEwVLxQIW543O4WrWYx_i2xI1KjGkh6hFbZvL7Cd3ueP1eqP2iOoTwKxCSt2TArtGIOe6-UsGHPDaCr8F-xL0nM4nEBxd7Ns1Hzh1B5oYMWLKTLg0J0vjQYm1TeLI_Vo6l70RaGkXbo%3D","Method":"GET"}]}
```

I would expect an array for endpoints that return multiple things, or an object for endpoints that return just one. In the example above, this would just be `[]`.

**Comment by zond** [comment]
I have a standardized method of creating responses, which includes links and data for every response.

Some responses contain lists, in which case the Properties is a list of items.

They all have names as well, to enable clients to verify that they get what they expect, and to help developers or users understand what's happening.

The description field is for developers to understand more about the details.

To simplify the entire system, and to make sure that the JSON and HTML responses both contain all relevant information, I don't filter out stuff in one or the other - they both should contain everything you need to proceed.

I don't see a big cost with doing it this way - App Engine automatically compresses responses if you tell it to, and parsing this data is arguably as easy as parsing a straight off list.

Changing it is however costly - it would introduce different behavior for JSON and HTML responses, reduce the level of verbosity and make responses follow different standards for lists and singular items.

Therefore, I don't think it's a good idea.

Please reopen if you want to argue your case :)
