### ISSUE TITLE
Glicko scoring

### ISSUE THREAD

**Issue by spamguy** [zond/diplicity#42]
In addition to the scoring algorithms already proposed, there is Glicko. See https://github.com/Kashomon/goglicko. Its perk is that it supports arbitrary numbers of teams with arbitrary members. For Diplomacy, 1 vs. 1 vs. 1 vs. etc. This is similar to Microsoft's Trueskill, but without the patent.

**Comment by zond** [comment]
Oh, this was very cool! I'll use Glicko instead of ELO :)

**Comment by zond** [comment]
Finally, fixed!
