### ISSUE TITLE
Power preferences

### ISSUE THREAD

**Issue by spamguy** [zond/diplicity#43]
This feature was available on PBEM judges and is worth keeping.

If permitted, users should be able to give power preferences when joining a game. On PBEM it resembled something like 'RET[GIF]A', meaning 'Russia first priority, England second, Turkey, equal third preference for Germany/Italy/France, and Austria last.' Obviously it doesn't have to be this elaborate, but something that distinguishes 'hell yes' from 'hell no' (perhaps from 'meh' as well).

It should be a game-level option, probably opt-out.

This sounds like an implementation of the [stable marriage problem](https://rosettacode.org/wiki/Stable_marriage_problem#Go).

**Comment by zond** [comment]
Yeah, Droidippy has this, and I'm for the feature, but it's not for the first release (unless someone else builds it).

**Comment by zond** [comment]
Fixed!
