### ISSUE TITLE
frequent "Unfortunately, Diplicity has stopped" messages

### ISSUE THREAD

**Issue by Flieh** [zond/diplicity#70]
apk installed on Moto G gen3 and gen4 both running marshmallow. The crash sends me back to the main menu.

**Comment by Flieh** [comment]
the crash occurs while previewing the map under staging games.

**Comment by zond** [comment]
I think/hope I've fixed it now, at least if you uninstall+ reinstall.

Also, wrong repository, post Android bugs in https://github.com/zond/android-diplicity/issues/
