### ISSUE TITLE
Anonymised player data

### ISSUE THREAD

**Issue by spamguy** [zond/diplicity#71]
There are several gameplay features that would need total anonymity from the API to work effectively, gunboat (no press + anonymous players) being the biggest amongst them. 'Anonymity' in this context means all identifying player information, ID included, is not present in API output.

There are two methods that come to mind:
* Wipe the JSON of all sensitive information. This is how end-to-end dipl.io did it.
* Create disposable mini-players that join full players to games.

**Comment by zond** [comment]
Wiping the JSON is what I do with email adresses for players of non-member games, and it's pretty straight forward.

**Comment by tttppp** [comment]
As well as for gunboat, this came up as a feature request for privacy concerned (or ugly?) players:
https://groups.google.com/forum/m/#!topic/diplicity-talk/8JZhREXGjt0

For gunboat it would need to be a game setting, for privacy it would need to be a player preference.

Presumably once gunboat games have finished then player information becomes published again?  What about after game chat in gunboat?

**Comment by zond** [comment]
Yeah, ability to turn off avatar (possibly replace it with a https://gravatar.com/) would be nice.

It's also related to the silent game feature of course.

I'm off the opinion that silent dippy (or two player dippy, for that matter) is kinda pointless, but I'm also off the opinion that any well implemented feature is welcome in diplicity.

And if I wanted to play silent (Gunboat? The definition varies I think) dippy I would want the player identities public after, AND the ability to chat after.

**Comment by zond** [comment]
"I'm of the opinion"

**Comment by tttppp** [comment]
Yes - two player diplomacy isn't really diplomacy. It does seem to be very popular though - presumably because people want to play a quick game immediately.

**Comment by zond** [comment]
Yeah - as I said - of someone is willing to put in the work to implement it well, then it has a place in the codebase :)

**Comment by JorenC** [comment]
I think this feature is now implemented, where GunBoat games become completely anonymous. Should we close this issue?

**Comment by zond** [comment]
Yeah, why not :)
