### ISSUE TITLE
next Phase on RDY

### ISSUE THREAD

**Issue by BlueTeck** [zond/diplicity#73]
Hi,

I am currently testing DIplicity (via your Android App). If I make my turn and set the phase settings to RDY, the next phase is starting immediately, even if the other players did not make any move/click and the deadline is not reached.

Game: ahJzfmRpcGxpY2l0eS1lbmdpbmVyEQsSBEdhbWUYgICAwMjFjAoM
I am Italy

-> I am not sure if this is a Android topic or not.

Regards,
Timo

**Comment by zond** [comment]
It's because all the other players are NMR flagged. Just like in Droidippy, the game doesn't wait for inactive players.

**Comment by zond** [comment]
Although, your game should end now - I fixed it so that games with only one active member stop automatically.

**Comment by BlueTeck** [comment]
Okay, thanks.
