### ISSUE TITLE
Sortable press in channel

### ISSUE THREAD

**Issue by spamguy** [zond/diplicity#75]
As far as I can tell press via /Game/X/Channel/Y/Messages can only be returned in one order, which is newest to oldest. This may not be the most logical order for all clients. The API method could receive an optional parameter like ?sort= to control which press appears first.

(Before you say anything, I agree the most recent press is usually the first that one wants to see. That's a client matter I can deal with.)

**Comment by zond** [comment]
Do you know of any client that wants a different order?

**Comment by spamguy** [comment]
Doing this client-side.
