### ISSUE TITLE
install Issues

### ISSUE THREAD

**Issue by feargswalsh92** [zond/diplicity#76]
My group and I are trying to add some features to the diplomacy game for a school project, however none of us can get through the diplicity setup instructions. 

We are stuck on step 3 when it tells us to run` goapp serve` in the app directory. It appears based on some Google searches that this command has been deprectaed and replaced by 
`gcloud app deploy` .

 However when we try this we get the following error message.
ERROR: The [application] field is specified in file [/Users/feargalwalsh/Downloads/diplicity/app/app.yaml]. This field is not used by gcloud and must be removed. Project name should instead be specified either by `gcloud config set project MY_PROJECT` or by setting the `--project` flag on individual command executions.
ERROR: (gcloud.app.deploy) Errors occurred while parsing the App Engine app configuration.

Any suggestions appreciated.

**Comment by zond** [comment]
`goapp serve` is evidently deprecated.

I changed the README to recommend `dev_appserver.py` instead (which is the original program that `goapp` wrapped anyway).

Running `dev_appserver.py .` should work.

`gcloud app deploy` rolls out to an App Engine service, and doesn't run the server locally.

**Comment by feargswalsh92** [comment]
So is the command dev_appserver.py or dev_appserver.py . ? Either way they're both not working but if it's dev_appserver.py which I suspect it is my terminal output is:
[-h] [-A APP_ID] [--host HOST] [--port PORT]
                        [--admin_host ADMIN_HOST] [--admin_port ADMIN_PORT]
                        [--auth_domain AUTH_DOMAIN] [--storage_path PATH]
                        [--log_level {debug,info,warning,critical,error}]
                        [--max_module_instances MAX_MODULE_INSTANCES]
                        [--use_mtime_file_watcher [USE_MTIME_FILE_WATCHER]]
                        [--threadsafe_override THREADSAFE_OVERRIDE]
                        [--php_executable_path PATH]
                        [--php_remote_debugging [PHP_REMOTE_DEBUGGING]]
                        [--php_gae_extension_path PATH]
                        [--php_xdebug_extension_path PATH]
                        [--appidentity_email_address APPIDENTITY_EMAIL_ADDRESS]
                        [--appidentity_private_key_path APPIDENTITY_PRIVATE_KEY_PATH]
                        [--python_startup_script PYTHON_STARTUP_SCRIPT]
                        [--python_startup_args PYTHON_STARTUP_ARGS]
                        [--jvm_flag JVM_FLAG] [--go_work_dir GO_WORK_DIR]
                        [--custom_entrypoint CUSTOM_ENTRYPOINT]
                        [--runtime RUNTIME] [--blobstore_path BLOBSTORE_PATH]
                        [--mysql_host MYSQL_HOST] [--mysql_port MYSQL_PORT]
                        [--mysql_user MYSQL_USER]
                        [--mysql_password MYSQL_PASSWORD]
                        [--mysql_socket MYSQL_SOCKET]
                        [--datastore_path DATASTORE_PATH]
                        [--clear_datastore [CLEAR_DATASTORE]]
                        [--datastore_consistency_policy {consistent,random,time}]
                        [--require_indexes [REQUIRE_INDEXES]]
                        [--auto_id_policy {sequential,scattered}]
                        [--logs_path LOGS_PATH]
                        [--show_mail_body [SHOW_MAIL_BODY]]
                        [--enable_sendmail [ENABLE_SENDMAIL]]
                        [--smtp_host SMTP_HOST] [--smtp_port SMTP_PORT]
                        [--smtp_user SMTP_USER]
                        [--smtp_password SMTP_PASSWORD]
                        [--smtp_allow_tls [SMTP_ALLOW_TLS]]
                        [--search_indexes_path SEARCH_INDEXES_PATH]
                        [--clear_search_indexes [CLEAR_SEARCH_INDEXES]]
                        [--enable_task_running [ENABLE_TASK_RUNNING]]
                        [--allow_skipped_files [ALLOW_SKIPPED_FILES]]
                        [--api_port API_PORT] [--grpc_api GRPC_APIS]
                        [--grpc_api_port GRPC_API_PORT]
                        [--automatic_restart [AUTOMATIC_RESTART]]
                        [--dev_appserver_log_level {debug,info,warning,critical,error}]
                        [--skip_sdk_update_check [SKIP_SDK_UPDATE_CHECK]]
                        [--default_gcs_bucket_name DEFAULT_GCS_BUCKET_NAME]
                        [--env_var ENV_VARIABLES]
                        [--google_analytics_client_id GOOGLE_ANALYTICS_CLIENT_ID]
                        [--google_analytics_user_agent GOOGLE_ANALYTICS_USER_AGENT]
                        yaml_path [yaml_path ...]
dev_appserver.py: error: too few arguments

**Comment by zond** [comment]
The arg to `dev_appserver.py` is the directory where the app.yaml file is.
If you're in the app dir it's `.`.
