### ISSUE TITLE
Readme says failed at the top 

### ISSUE THREAD

**Issue by CNWNMURRAY** [zond/diplicity#78]
Wanted some clarification on what the issue may be with CircleCl 2.0 build?

**Comment by zond** [comment]
I think circleci changed something with their directory layout. And I haven't had the energy to fox it.

The error is

mv -v $HOME/diplicity $HOME/.go_workspace/src/github.com/zond/diplicity
mv: cannot move ‘/home/ubuntu/diplicity’ to ‘/home/ubuntu/.go_workspace/src/github.com/zond/diplicity’: No such file or directory

mv -v $HOME/diplicity $HOME/.go_workspace/src/github.com/zond/diplicity returned exit code 1

Action failed: mv -v $HOME/diplicity $HOME/.go_workspace/src/github.com/zond/diplicity

**Comment by zond** [comment]
We removed that a while ago, I think.
