### ISSUE TITLE
Invitational games

### ISSUE THREAD

**Issue by tttppp** [zond/diplicity#86]
This came up in the forum: https://groups.google.com/forum/m/#!topic/diplicity-talk/rEl7GiPLfF8

It would be easy enough to have flag on each game, and filter them from the various games lists unless the user has joined them. A user should be able to join directly using the game id.

As mentioned in the forum thread, private games should not count towards ratings or quickness. I'm not sure how hatered works exactly, so I don't know if you could abuse the hating system with private games.

**Comment by zond** [comment]
I think all stats that related to actual games should exclude private games. As hater/hated and the rest of the ban system isn't related (in the database sense) to games at all, I think they could work the normal way still.

**Comment by zond** [comment]
Fixed!
