### ISSUE TITLE
Games where communication stays private

### ISSUE THREAD

**Issue by tttppp** [zond/diplicity#87]
I'm not sure if we want this feature or not, but it was suggested in the forum and used to be on Droidippy: https://groups.google.com/forum/m/#!topic/diplicity-talk/eht_RgA3CXs

This would be a communication mode (in the same way as gunboat), which meant that all messages weren't published after the end of the game.

Would it hinder self-moderation of games?

**Comment by zond** [comment]
It would make abuse likelier in those games, since y wouldn't have to be publicised as an asshole, but otherwise it would work I guess. Other players could still ban or mute you.

**Comment by tttppp** [comment]
I'm going to close this as I don't want it (I'm too nosy). If someone else feels like implementing it then go ahead.
