### ISSUE TITLE
Option to accept defeat

### ISSUE THREAD

**Issue by tttppp** [zond/diplicity#88]
Currently we have an "accept draw" option. We could add an "accept defeat" button that would end the game with a solo if all but one player accepted defeat.  This option would imply "accept draw", so the game would end in a draw if all players selected one of the two options.

Note that Droidippy had a more complicated system that confused people:

https://groups.google.com/forum/m/#!topic/diplicity-talk/lwvPjeKiDxc

**Comment by zond** [comment]
It shouldn't be hard to implement, even if I don't really see the point. A leader that demands a solo should have to WORK for it!

**Comment by Enriador** [comment]
"Accept surrender" goes against the spirit of the game. A player should always fight to the end, even if just as a kingmaker or for petty revenge.

Allan Calhamer himself exposed this view. Check his article "Objectives Other Than Winning" on dipwiki.com

**Comment by Enriador** [comment]
On that regard, even "Accept Draw" is bad. If you still have pieces on the board you should be part of the draw since you are still part of the game!

**Comment by zond** [comment]
That's how draw works today - a draw always includes all survivors.

**Comment by Enriador** [comment]
Indeed, thankfully! I just wanted to point out that suggestions to change
the status quo, while giving some extra flexibility, actually goes against
the game's design itself, and makes the endgame even more stagnant.

Em 08/10/2017 13:56, "zond" <notifications@github.com> escreveu:

> That's how draw works today - a draw always includes all survivors.
>

**Comment by zond** [comment]
I agree, but I also see no problem with adding options when you create a
game, so that people who actually want a more complex (and less canonical)
end-game rule could get that.

OTOH, I don't want to play with those rules myself, so my already pretty
non-existent time for diplicity development will probably not go to that.

**Comment by tttppp** [comment]
I'm happy with the current behaviour too, so I'll close this.
