### ISSUE TITLE
Allow navigation between phases within the orders view

### ISSUE THREAD

**Issue by bsweezy** [zond/diplicity#89]
When looking at the orders view (see attached), it would be helpful to be able to click to go back a phase to see the detailed orders/resolution without navigating the menu. Maybe add little phase forward and backward arrows to the bottom of the orders screen? (I think that's how droidippy worked).

![image](https://user-images.githubusercontent.com/2927543/28755220-ca9f7f62-7523-11e7-85df-515f62e97644.png)

===========
A group of 7 of us did a live game yesterday around a physical board game map, where we used iphones, ipads, and android devices to play the same game--this is one of a series of issues we opened related to our experience. It was a great overall experience! I'm so impressed at this project's progress.

**Comment by zond** [comment]
Most views have the swipe left/right navigation between phases. It's s bit
hidden, but the orders view has it as well. Try it out!

**Comment by bsweezy** [comment]
Oh I did not know that! However, I just tried ~50 times (putting my finger
on the right and dragging it leftward on the orders screen) and it only
worked once so it might need some attention.

**Comment by zond** [comment]
One needs to be quick :)

**Comment by tttppp** [comment]
Closing this, as it's a client issue - issue raised here instead: https://github.com/zond/android-diplicity/issues/57
