### ISSUE TITLE
Number of units and number of centres in API

### ISSUE THREAD

**Issue by tttppp** [zond/diplicity#91]
There was a request from the dipl.io client to add something to make it easier to find how many units a player can build our dispand in the adjustment phase:

https://github.com/spamguy/dipl.io/issues/43

Returning counts of the number of units and number of centers would probably be generic enough for all variants, and would also help with the Android client issue about displaying the center count for all nations.

**Comment by tttppp** [comment]
For reference the current API returns the following:
```
    "Units": [
      {
        "Province": "vie",
        "Unit": {
          "Type": "Army",
          "Nation": "Austria"
        }
      },
      ...
    ]
    "SCs": [
      {
        "Province": "kie",
        "Owner": "Germany"
      },
      ...
    ]
```

IMO it's not exactly hard for the client to determine the number of units and SCs that a player has from this.  It is quite a bit harder to determine how many units the player can build (e.g. because home centres might be blocked).

**Comment by zond** [comment]
I guess the options API call has to get some more data, for the client to
be able to show the best info.

**Comment by tttppp** [comment]
Closing this as it was pretty straightforward to determine the right values when implementing the phase status feature in android-diplicity.
