### ISSUE TITLE
Player has too many units after adjustment in Ancient Med

### ISSUE THREAD

**Issue by tttppp** [zond/diplicity#92]
See Fall 7 Adjustment in this game:
https://diplicity-engine.appspot.com/Game/ahJzfmRpcGxpY2l0eS1lbmdpbmVyEQsSBEdhbWUYgICAwI6gjQoM

Carthage only selected one unit to disband, but was meant to select three. The engine let them keep all the unselected units.

Possibly relevant is that they reported the app wasn't responding during adjustment, although the engine should cope with whatever the client sends it.

**Comment by zond** [comment]
Network or server problems shouldn't affect the adjudication...

Is it possible to create a test case that reproduces the error?

**Comment by tttppp** [comment]
I now have a test case to reproduce this. I haven't played around with it too much, but it seems like automatic removal doesn't happen. 

Incidentally I think I should have raised this against godip.

**Comment by zond** [comment]
Automatic removal - I think DATC has a test case for that, DATC requires
furthest units to be removed first. Weird.

**Comment by tttppp** [comment]
Yep, I wonder if I disabled it for the variant. DATC definitely has a test case or ten for it. :-)

**Comment by zond** [comment]
I don't see how a variant would disable that :O

The adjudicator calls PostProcess on the resulting phase, and the classical
Phase (that I think all variants use?) adjusts units in that method...
Haven't traced through the code yet, but I'm preliminarily confused :)

**Comment by tttppp** [comment]
I just checked the Classical variant, and it successfully disbanded some units for me in a game where I needed to lose units.

**Comment by zond** [comment]
So, do you have your test case (that reproduces) in a pull request or
something?

**Comment by tttppp** [comment]
On my machine. I'll push it tomorrow, on my phone now. (Mental note: remember to push changes in future)

**Comment by tttppp** [comment]
The test case is here: https://github.com/zond/godip/pull/18

**Comment by zond** [comment]
Should be fixed after merge of https://github.com/zond/godip/pull/18
