### ISSUE TITLE
API suggests moving armies to Baleares 

### ISSUE THREAD

**Issue by tttppp** [zond/diplicity#93]
When trying to make the move then the Android app says Internal Server Error.

In particular I noticed this when trying to move from Saguntum in Spring 8 of this game:

https://diplicity-engine.appspot.com/Game/ahJzfmRpcGxpY2l0eS1lbmdpbmVyEQsSBEdhbWUYgICAwI6gjQoM

**Comment by zond** [comment]
Does the server log (accessible from the Cloud console) show any errors?

**Comment by tttppp** [comment]
Fixed on master.
