### ISSUE TITLE
Probation function is gone

### ISSUE THREAD

**Issue by regdot** [zond/diplicity#95]
Idle players can't be ignored by the game, so we have to wait every turn until the deadline.

**Comment by zond** [comment]
What makes you think so? Nothing has changed in the code...

**Comment by regdot** [comment]
To be fair, it's the first turn of our game.

**Comment by zond** [comment]
So, you have no reason to believe your complaint has any merit? Or do I
misunderstand? :)

**Comment by tttppp** [comment]
I think the game is this one: https://diplicity-engine.appspot.com/Game/ahJzfmRpcGxpY2l0eS1lbmdpbmVyEQsSBEdhbWUYgICAoJC3jgkM
Carthage hasnt made any orders and the phases have been less than 24 hours long, so I think everything is fine.

Please reopen if I've made a mistake! Also thanks for getting involved! :-)
