### ISSUE TITLE
Games don't end when all but one is quitter

### ISSUE THREAD

**Issue by zond** [zond/diplicity#96]
https://github.com/zond/diplicity/blob/master/game/phase.go#L575 should probably be "-2" instead of "-1" to let games end when they should.

What do you think @tttppp ?

**Comment by tttppp** [comment]
I agree. Maybe you meant `=n-1`?

The downside of this is that missing a phase in a two player game becomes a resignation. Not a big issue, but I expect some people will be caught by surprise.

**Comment by zond** [comment]
Yeah, and I also realized that ending a game in a draw just because you're
the only player left might do weird things to the scoring and rating system.

Maybe think about it a while before changing..

**Comment by tttppp** [comment]
I think it should be a win if you're the only player left, shouldn't it? Unless you only have one unit you should be able to force a win (against NMRs) anyway.

I guess there's also a really unlikely edge case where your two units are separated too.

**Comment by zond** [comment]
The problem is if you have two players remaining, and one is slowly losing.

Right now if they go NMR, the other player can just continue to a solo
without much risk.

If we make games end when only one player remains, it would instead end
early and sort of evenly.

And since score is assigned based on SCs it would make it easy to kill
games before you really lose a lot.

**Comment by tttppp** [comment]
I was thinking it would be the same as a solo win. One player gets all the rating points, everyone else gets nothing. (At least I think that's how it works)

**Comment by zond** [comment]
Not now - now the points are always distributed via sum squares regardless
of NMR or active status.
